services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paganahora
    restart: unless-stopped
    working_dir: /var/www/html
    command: bash -c "php artisan cache:clear && php artisan route:cache && php artisan serve --host 0.0.0.0 --port=9000"
    ports:
      - 9005:9000
    volumes:
      - ./:/var/www/html
    network_mode: bridge